version: '3'
services:
  front:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        dir: forecast-front
    command: npm start
    working_dir: /forecast-front
    volumes:
      - ./forecast-front:/forecast-front
      - /forecast-front/node_modules
    ports:
      - "3000:3000"
